spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/involvement_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  sql:
    init:
      platform: postgresql
springdoc:
  swagger-ui:
    url: /api-doc.yml
