openapi: '3.0.3'
info:
  title: Involvement System
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: member
    description: Члены гильдий/сообществ
  - name: guild
    description: Гильдии/сообщества
  - name: level
    description: Профессиональные уровни членов гильдий
  - name: department
    description: Отделы, отражающие структуры компании
  - name: position
    description: Должность члена гильдии в компании

paths:
  /api/v1/members:
    get:
      summary: Получить список членов гильдий постранично
      operationId: getMembers
      tags:
        - member
      parameters:
        - in: query
          name: page
          description: Номер страницы (нумерация начинается с 1)
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          example: 1
        - in: query
          name: size
          description: Размер страницы (сколько участников выведется)
          allowEmptyValue: true
          schema:
            type: integer
            default: 20
          example: 20
        - in: query
          name: fullName
          description: Контекстный регистронезависимый поиск в имени
          allowEmptyValue: true
          schema:
            type: string
          example: иван
        - in: query
          name: departmentId
          description: Идентификатор отдела
          allowEmptyValue: true
          schema:
            type: integer
            format: int64
          example: 32
        - in: query
          name: positionId
          description: Идентификатор должности
          allowEmptyValue: true
          schema:
            type: integer
            format: int64
          example: 27
        - in: query
          name: guildId
          description: Идентификатор гильдии
          allowEmptyValue: true
          schema:
            type: integer
            format: int64
          example: 5
        - in: query
          name: levelId
          description: Идентификатор уровня в гильдии
          allowEmptyValue: true
          schema:
            type: integer
            format: int64
          example: 2

      responses:
        '200':
          description: Страница со списком участников
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberRatingPageResponse'
  /api/v1/members/top:
    get:
      summary: Получить список топ-20 членов гильдий
      operationId: getMembersTop
      tags:
        - member
      responses:
        '200':
          description: Страница со списком топ-20 участников
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MemberRatingResponse'
  /api/v1/members/{id}:
    get:
      summary: Получить участника по идентификатору
      operationId: getMemberById
      tags:
        - member
      parameters:
        - in: path
          name: id
          description: Идентификатор участника
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      responses:
        '200':
          description: Информация об участнике
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'

  /api/v1/guilds:
    get:
      summary: Получить список гильдий
      operationId: getGuilds
      tags:
        - guild
      responses:
        '200':
          description: Список гильдий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GuildResponse'

  /api/v1/levels:
    get:
      summary: Получить список уровней гильдий
      operationId: getLevels
      tags:
        - level
      responses:
        '200':
          description: Список уровней гильдий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LevelResponse'

  /api/v1/departments:
    get:
      summary: Получить список отделов
      operationId: getDepartments
      tags:
        - department
      responses:
        '200':
          description: Список отделов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DepartmentResponse'
  /api/v1/departments/{parentId}/subsidiaries:
    get:
      summary: Получить список подчиненных отделов по идентификатору родителя
      operationId: getDepartmentsByParentId
      tags:
        - department
      parameters:
        - in: path
          name: parentId
          description: Идентификатор родительского подразделения
          required: true
          schema:
            type: integer
            format: int64
          example: 1
      responses:
        '200':
          description: Список подчиненных отделов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DepartmentResponse'

  /api/v1/positions:
    get:
      summary: Получить список должностей
      operationId: getPositions
      tags:
        - position
      responses:
        '200':
          description: Список должностей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PositionResponse'


components:
  schemas:
    MemberRatingResponse:
      type: object
      description: Рейтинг члена гильдии / участника сообщества
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор участника
          example: 101
        fullName:
          type: string
          description: Полное имя участника (Фамилия, Имя, Отчество)
          example: Иванов Иван Иванович
        rating:
          type: integer
          description: Рейтинг участника
          example: 333
    MemberRatingPageResponse:
      type: object
      description: Страница членов гильдии
      properties:
        content:
          description: Список членов гильдии
          type: array
          items:
            $ref: '#/components/schemas/MemberRatingResponse'
          example:
            - id: 101
              fullName: Иванов Иван Иванович
              rating: 333
            - id: 213
              fullName: Обломов Павел Викторович
              rating: 199
        page:
          description: Номер страницы
          type: integer
          example: 1
        size:
          description: Размер страницы (количество участников)
          type: integer
          example: 20
        totalItems:
          description: Всего участников
          type: integer
          format: int64
          example: 2
        totalPages:
          description: Всего страниц
          type: integer
          example: 1
    MemberResponse:
      type: object
      description: Информация о члене гильдии / участнике сообщества
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор участника
          example: 101
        fullName:
          type: string
          description: Полное имя участника (Фамилия, Имя, Отчество)
          example: Иванов Иван Иванович
        rating:
          type: integer
          description: Рейтинг участника
          example: 333
        phone:
          type: string
          description: Телефон участника
          example: +79990010001
        email:
          type: string
          description: ivaniv_ii@our-company.mock
        department:
          type: string
          description:  Наименование отдела, в котором работает участник
          example: Отдел разработки
        position:
          type: string
          description:  Наименование должности участника
          example: Ведущий Java-разработчик
        guild:
          type: string
          description:  Наименование гильдии
          example: Сообщество Java-разработчиков
        level:
          type: string
          description:  Уровень участника по шкале градаций гильдии
          example: 3 уровень
        publicKey:
          type: string
          description:  Публичный ключ кошелька участника
          example: 0x15Cc4abzz27647ec9fE70D892E55586074263dF0

    GuildResponse:
      type: object
      description: Информация о гильдии/сообществе
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор гильдии
          example: 1
        name:
          type: string
          description: Названии гильдии
          example: Сообщество Java-разработчиков

    LevelResponse:
      type: object
      description: Информация о профессиональном уровне
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор уровня
          example: 1
        name:
          type: string
          description: Название уровня
          example: 3
        guildName:
          type: string
          description: Название гильдии, к которой относится уровень
          example: Сообщество Java-разработчиков
        minRating:
          type: integer
          description: Минимальный уровень рейтинга участника, необходимый для включения в гильдию

    DepartmentResponse:
      type: object
      description: Информация об отделе
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор отдела
          example: 10
        name:
          type: string
          description: Название отдела
          example: 3
        parentId:
          type: integer
          format: int64
          description: Идентификатор вышестоящего отдела
          example: 4
        head:
          type: string
          description: Полное имя руководителя отдела
          example: Самохвалов Илья Петрович

    PositionResponse:
      type: object
      description: Должность
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор должности
          example: 1
        name:
          type: string
          description: Название должности
          example: 3

